config-version: 2
name: 'quickbooks'

<<<<<<< HEAD
version: '1.2.1'
=======
version: '1.2.0'
>>>>>>> b8c82849da1b996bab027e5e75463b9e46c9fadb

require-dbt-version: [">=1.3.0", "<3.0.0"]

models:
  quickbooks:
    +materialized: table
    +schema: quickbooks
    double_entry_transactions:
      +schema: quickbooks_intermediate
      +materialized: table
    transaction_lines:
      +materialized: ephemeral
    intermediate:
      +materialized: ephemeral
    staging:
      +schema: quickbooks_staging
      +materialized: table
      tmp:
        +materialized: view 

vars:
  quickbooks:
    account: "{{ source('quickbooks', 'account') }}"
    address: "{{ source('quickbooks', 'address') }}"
    bill_line: "{{ source('quickbooks', 'bill_line') }}"
    bill_linked_txn: "{{ source('quickbooks', 'bill_linked_txn') }}"
    bill_payment_line: "{{ source('quickbooks', 'bill_payment_line') }}"
    bill_payment: "{{ source('quickbooks', 'bill_payment') }}"
    bill: "{{ source('quickbooks', 'bill') }}"
    bundle_item: "{{ source('quickbooks', 'bundle_item') }}"
    bundle: "{{ source('quickbooks', 'bundle') }}"
    credit_memo_line: "{{ source('quickbooks', 'credit_memo_line') }}"
    credit_memo: "{{ source('quickbooks', 'credit_memo') }}"
    credit_card_payment_txn: "{{ source('quickbooks', 'credit_card_payment_txn') }}"
    customer: "{{ source('quickbooks', 'customer') }}"
    department: "{{ source('quickbooks', 'department') }}"
    deposit_line: "{{ source('quickbooks', 'deposit_line') }}"
    deposit: "{{ source('quickbooks', 'deposit') }}"
    estimate: "{{ source('quickbooks', 'estimate') }}"
    estimate_line: "{{ source('quickbooks', 'estimate_line') }}"
    invoice_line: "{{ source('quickbooks', 'invoice_line') }}"
    invoice_line_bundle: "{{ source('quickbooks', 'invoice_line_bundle') }}"
    invoice_linked_txn: "{{ source('quickbooks', 'invoice_linked_txn') }}"
    invoice: "{{ source('quickbooks', 'invoice') }}"
    invoice_tax_line: "{{ source('quickbooks','invoice_tax_line') }}"
    item: "{{ source('quickbooks', 'item') }}"
    journal_entry_line: "{{ source('quickbooks', 'journal_entry_line') }}"
    journal_entry: "{{ source('quickbooks', 'journal_entry') }}"
    journal_entry_tax_line: "{{ source('quickbooks','journal_entry_tax_line') }}"
    payment_line: "{{ source('quickbooks', 'payment_line') }}"
    payment: "{{ source('quickbooks', 'payment') }}"
    purchase_line: "{{ source('quickbooks', 'purchase_line') }}"
    purchase: "{{ source('quickbooks', 'purchase') }}"
    purchase_tax_line:  "{{ source('quickbooks','purchase_tax_line') }}"
    purchase_order_line: "{{ source('quickbooks','purchase_order_line') }}"
    purchase_order: "{{ source('quickbooks','purchase_order') }}"
    purchase_order_linked_txn: "{{ source('quickbooks','purchase_order_linked_txn') }}"
    refund_receipt_line: "{{ source('quickbooks', 'refund_receipt_line') }}"
    refund_receipt: "{{ source('quickbooks', 'refund_receipt') }}"
    refund_receipt_tax_line: "{{ source('quickbooks','refund_receipt_tax_line') }}"   
    sales_receipt_line: "{{ source('quickbooks', 'sales_receipt_line') }}"
    sales_receipt: "{{ source('quickbooks', 'sales_receipt') }}"
    sales_receipt_tax_line: "{{ source('quickbooks','sales_receipt_tax_line') }}"    
    tax_agency: "{{ source('quickbooks','tax_agency') }}"
    tax_rate: "{{ source('quickbooks','tax_rate') }}"
    transfer: "{{ source('quickbooks', 'transfer') }}"
    vendor_credit_line: "{{ source('quickbooks', 'vendor_credit_line') }}"
    vendor_credit: "{{ source('quickbooks', 'vendor_credit') }}"
    vendor: "{{ source('quickbooks', 'vendor') }}"

    financial_statement_ordinal: []
    cash_flow_statement_type_ordinal: []

    using_address: true
    using_bill: true
    using_credit_memo: true
    using_department: true
    using_deposit: true
    using_estimate: true
    using_invoice: true
    using_invoice_bundle: true
    using_journal_entry: true
    using_payment: true
    using_refund_receipt: true
    using_transfer: true
    using_vendor_credit: true
    using_sales_receipt: true
    using_credit_card_payment_txn: false
    using_purchase_order: false
    using_purchase_tax_line: false
    using_sales_receipt_tax_line: false
    using_refund_receipt_tax_line: false
    using_invoice_tax_line: false
    using_tax_agency: false
    using_tax_rate: false

analysis-paths: ["analysis"]
clean-targets:
- target
- dbt_modules
- dbt_packages
